# -*- coding: utf-8 -*-
"""annotation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10PZy4NSHa3CtM5VSa29tLSQ4OYQMldu5
"""

# Python program to read
# json file
import json

# Opening JSON file
f = open('train_demo.json')
# Code for printing to a file
out = open('test_demo.json', 'w')

# returns JSON object as
# a dictionary
data = json.load(f)

# Iterating through the json
# list
for dialogue in data["data"]:
	if dialogue["speaker"] == "A":
		str = ""
		if not "expanded emotion cause span" in dialogue:
			str += "None"
	 	
		else:
			cnt = 0
			str = ""
			length = len(dialogue["expanded emotion cause span"])
			for keyword in dialogue["expanded emotion cause span"]:
				str += keyword
				cnt += 1
				if cnt != length:
					str += " [SEP] "

		print("{\"query\": {\"text\": \"" + dialogue["utterance"] + "\", \"label\": \"" + dialogue["emotion"] + "\", \"keywords\": \"" + str + "\"},", end = " ", file = out)
	 
	else:
		print("\"reply\": {\"reply_label\": \"None\", \"text\": \"" + dialogue["utterance"] + "\"}}", file = out)
# Closing file
f.close()
out.close()

# Python program to read
# json file
import json

# Opening JSON file
f2 = open('test.json')

# returns JSON object as
# a dictionary
data2 = json.load(f2)

unique_list = set()

# Iterating through the json
# list
for dialogue in data2["data"]:
	unique_list.update(dialogue["reply"]["reply_label"].split(","))
for x in unique_list:
  print(x)

# Python program to read
# json file
import json
import pandas as pd

# Opening JSON file
f3 = open('train_demo.json')

# returns JSON object as
# a dictionary
data3 = json.load(f3)

reply_list = list()

# Iterating through the json
# list
for dialogue in data["data"]:
  if dialogue["speaker"] == "B":
    reply_list.append(dialogue["utterance"])

df = pd.DataFrame(reply_list)
df